# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultiGitter < Formula
  desc "Update multiple repositories in bulk."
  homepage ""
  version "0.20.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.2/multi-gitter_0.20.2_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "53a201d24f20eb8c321d70f19d7ab4c99429691aeb275f553dff3353ab3709fe"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.2/multi-gitter_0.20.2_Darwin_ARM64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "3b0daf8958ece56cff5d5fe6468a27a24ac971be3e239aa468032be927163e6d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.2/multi-gitter_0.20.2_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "6dffc5996c41446f464ecd677f5b4ad1f34911bff091dc782a112dfaa7aa4688"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.2/multi-gitter_0.20.2_Linux_ARMv6.tar.gz", :using => CurlDownloadStrategy.
    sha256 "553f4bc5b89a3c8c979b2a1588a27c6e0c819c198891f1442ea44c6bd0c191d3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.2/multi-gitter_0.20.2_Linux_ARM64.tar.gz", :using => CurlDownloadStrategy.
    sha256 "a0e202636850e97436802a5236c9bef470388a20d6afac09a3f2582571468c83"
  end

  def install
    bin.install "multi-gitter"
  end

  test do
    system "#{bin}/program version"
  end
end
