# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultiGitter < Formula
  desc "Update multiple repositories in bulk"
  homepage "https://github.com/lindell/multi-gitter"
  version "0.20.4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.4/multi-gitter_0.20.4_Darwin_x86_64.tar.gz"
    sha256 "5714546ee74898326c9001a20b10db73c3eb93202dc0a8752426da40fc67c67f"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.4/multi-gitter_0.20.4_Darwin_ARM64.tar.gz"
    sha256 "72f744ea47e57899124826eb996eede2a223bfb094ebbea1dc3891aacda8d76d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.4/multi-gitter_0.20.4_Linux_x86_64.tar.gz"
    sha256 "e21d858d0cd1e9411b7c7079f7c3290640d4a6af70427db8f3798302f8934e52"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.4/multi-gitter_0.20.4_Linux_ARMv6.tar.gz"
    sha256 "be5327f93b7bdbd7d37e0e9d91ac89c161b93de541f386c3206001fca65b2297"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.20.4/multi-gitter_0.20.4_Linux_ARM64.tar.gz"
    sha256 "1f6b1eeddef31b577c70e2983a344bc036c8c1ebc76c368756c35ba24fbf4fcc"
  end

  def install
    bin.install "multi-gitter"
  end

  test do
    system "#{bin}/multi-gitter version"
  end
end
