# This file was generated by GoReleaser. DO NOT EDIT.
cask "multi-gitter" do
  name "multi-gitter"
  desc "Update multiple repositories in bulk"
  homepage "https://github.com/lindell/multi-gitter"
  version "0.61.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "multi-gitter"
  bash_completion "completions/multi-gitter.bash"
  zsh_completion "completions/multi-gitter.zsh"
  fish_completion "completions/multi-gitter.fish"

  on_macos do
    on_intel do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "8712e54d0e351cb85d21433487ae5dcc7de5ac8552a87e3ea472290f7bdb0075"
    end
    on_arm do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Darwin_ARM64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "e46f069ca37ba2f0263ded9574338397809a3ee1b28b59c03ed52e86ea2f3c23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "b579ed6c86b313e1c02f662356b5ea24408e86d11987dbdb0d6fc5fa6282f92f"
    end
    on_arm do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Linux_ARM64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "652c4baa0f43b0f8b93b771e6f320fc9b6cb2bbc43b132ecb807a7fc1406e941"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/multi-gitter"]
    end
  end

  # No zap stanza required
end
