# This file was generated by GoReleaser. DO NOT EDIT.
cask "multi-gitter" do
  name "multi-gitter"
  desc "Update multiple repositories in bulk"
  homepage "https://github.com/lindell/multi-gitter"
  version "0.62.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "multi-gitter"
  bash_completion "completions/multi-gitter.bash"
  zsh_completion "completions/multi-gitter.zsh"
  fish_completion "completions/multi-gitter.fish"

  on_macos do
    on_intel do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "92cefd08fc5ac3d80def58285eb097ac7109fa058025e516104dd62c8b3d4679"
    end
    on_arm do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Darwin_ARM64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "f0a71b48ae6f8925b063700b0d25ed1f85584f339c6d70b1b1e73a35ed2730b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "4394a93fc39daaa5a89af5a202251b3731fb6ed496bd12ebc46016b54d96d05f"
    end
    on_arm do
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Linux_ARM64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
      sha256 "497fdc7afe3a3cf4b37b9152cd675177cd2d8c86a7ad9b1b13e79fb8d959afd5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/multi-gitter"]
    end
  end

  # No zap stanza required
end
