# This file was generated by GoReleaser. DO NOT EDIT.
cask "multi-gitter" do
  version "0.63.1"

  on_macos do
    on_intel do
      sha256 "a3dbdad6bf505ff0ccf5ee1e7f4304869767a2e293f294453d64a59a3b47f8fd"
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
    end
    on_arm do
      sha256 "df3ea56fe2fb5684a4634e00de3c69082a64b09fd68a7cf1c4169ebab92de49b"
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Darwin_ARM64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
    end
  end

  on_linux do
    on_intel do
      sha256 "94711a96c75975be9cfd9f3bd1d94a371b85716ac40be35f50b7b4cd271caf8d"
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
    end
    on_arm do
      sha256 "f4afde8bf0ab46a433901615e579f3c139ee0347162d615399d4e805e622c1ea"
      url "https://github.com/lindell/multi-gitter/releases/download/v#{version}/multi-gitter_#{version}_Linux_ARM64.tar.gz",
        verified: "github.com/lindell/multi-gitter"
    end
  end

  name "multi-gitter"
  desc "Update multiple repositories in bulk"
  homepage "https://github.com/lindell/multi-gitter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "multi-gitter"
  bash_completion "completions/multi-gitter.bash"
  fish_completion "completions/multi-gitter.fish"
  zsh_completion "completions/multi-gitter.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/multi-gitter"]
    end
  end

  # No zap stanza required

end
