# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultiGitter < Formula
  desc "Update multiple repositories in bulk"
  homepage "https://github.com/lindell/multi-gitter"
  version "0.22.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.22.1/multi-gitter_0.22.1_Darwin_x86_64.tar.gz"
    sha256 "01958809039db43ecadfe8db1368d6fe6bd1e12d74633b2f54393e30cc168020"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.22.1/multi-gitter_0.22.1_Darwin_ARM64.tar.gz"
    sha256 "7fccf61368fd39078b1b3c90804b63251f4ce3af25c38080a8d734f4abb7f336"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.22.1/multi-gitter_0.22.1_Linux_x86_64.tar.gz"
    sha256 "da8a06c9df5650cc1b1351c3f7181288ff25a5b8f2155a28b8f6dfdd89047c6e"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.22.1/multi-gitter_0.22.1_Linux_ARMv6.tar.gz"
    sha256 "40f07f808662c43bfd7faa149384e5050b2465148bee560aa3e6348affdebc69"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/lindell/multi-gitter/releases/download/v0.22.1/multi-gitter_0.22.1_Linux_ARM64.tar.gz"
    sha256 "fac5b046b3ee67ba2e6fd3dffd914c137bf7893c8110e9673b44365e11e5118d"
  end

  def install
    bin.install "multi-gitter"
    bash_completion.install "completions/multi-gitter.bash" => "multi-gitter"
    zsh_completion.install "completions/multi-gitter.zsh" => "_multi-gitter"
    fish_completion.install "completions/multi-gitter.fish"
  end

  test do
    system "#{bin}/multi-gitter version"
  end
end
