# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MultiGitter < Formula
  desc "Update multiple repositories in bulk"
  homepage "https://github.com/lindell/multi-gitter"
  version "0.59.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lindell/multi-gitter/releases/download/v0.59.0/multi-gitter_0.59.0_Darwin_x86_64.tar.gz"
      sha256 "62bae28a10baf13a04ed83ae51426475ee7f2f11688dbc1bad32e1bf944ba06f"

      def install
        bin.install "multi-gitter"
        bash_completion.install "completions/multi-gitter.bash" => "multi-gitter"
        zsh_completion.install "completions/multi-gitter.zsh" => "_multi-gitter"
        fish_completion.install "completions/multi-gitter.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lindell/multi-gitter/releases/download/v0.59.0/multi-gitter_0.59.0_Darwin_ARM64.tar.gz"
      sha256 "1b0083f8be400bf889ee7c7fe6f8544f11138e482d99e07d60874b824da694e3"

      def install
        bin.install "multi-gitter"
        bash_completion.install "completions/multi-gitter.bash" => "multi-gitter"
        zsh_completion.install "completions/multi-gitter.zsh" => "_multi-gitter"
        fish_completion.install "completions/multi-gitter.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/multi-gitter/releases/download/v0.59.0/multi-gitter_0.59.0_Linux_x86_64.tar.gz"
      sha256 "03a6136756a6b7f2a723e6e7c55c49e1decb6bafa088c3f73612031fa1488aed"
      def install
        bin.install "multi-gitter"
        bash_completion.install "completions/multi-gitter.bash" => "multi-gitter"
        zsh_completion.install "completions/multi-gitter.zsh" => "_multi-gitter"
        fish_completion.install "completions/multi-gitter.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/multi-gitter/releases/download/v0.59.0/multi-gitter_0.59.0_Linux_ARM.tar.gz"
      sha256 "1ed1ef21d3b8385d4902e31e5ddc4fe350e9a6ada90a4d90a0c2218449e62bd9"
      def install
        bin.install "multi-gitter"
        bash_completion.install "completions/multi-gitter.bash" => "multi-gitter"
        zsh_completion.install "completions/multi-gitter.zsh" => "_multi-gitter"
        fish_completion.install "completions/multi-gitter.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lindell/multi-gitter/releases/download/v0.59.0/multi-gitter_0.59.0_Linux_ARM64.tar.gz"
      sha256 "fb61dc8b60239fc93b0caa7489a448c94fa1d1ab3a21b083016cd41023a47141"
      def install
        bin.install "multi-gitter"
        bash_completion.install "completions/multi-gitter.bash" => "multi-gitter"
        zsh_completion.install "completions/multi-gitter.zsh" => "_multi-gitter"
        fish_completion.install "completions/multi-gitter.fish"
      end
    end
  end

  test do
    system "#{bin}/multi-gitter", "version"
  end
end
